[workspace]
release_commits = "^(feat|fix|perf)[(!:]"

[changelog]
commit_parsers = [
  { message = "^feat", group = "Added" },
  { message = "^fix", group = "Fixed" },
  { message = "^perf", group = "Performance" },
  { message = "^doc", group = "Documentation" },
  { message = "^refactor", group = "Changed" },
  { message = "^test", skip = true },
  { message = "^ci", skip = true },
  { message = "^build", skip = true },
  { message = "^chore", skip = true },
]
